import html2pdf from 'html2pdf.js';

export const exportToPDF = (review, code, language) => {
  const content = document.createElement('div');
  content.innerHTML = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #333;">
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #10b981; margin: 0; font-size: 28px;">📋 Code Review Report</h1>
        <p style="color: #666; margin-top: 10px;">Generated by CodeReview AI</p>
        <p style="color: #999; font-size: 12px;">${new Date().toLocaleString()}</p>
      </div>

      <div style="background: linear-gradient(135deg, #10b981 0%, #06b6d4 100%); color: white; padding: 20px; border-radius: 12px; margin-bottom: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <div>
            <h2 style="margin: 0; font-size: 18px;">Overall Score</h2>
            <p style="margin: 5px 0 0; opacity: 0.9; font-size: 14px;">Based on AI analysis</p>
          </div>
          <div style="font-size: 48px; font-weight: bold;">${review.score}/10</div>
        </div>
      </div>

      <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin-bottom: 20px;">
        <h3 style="color: #10b981; margin: 0 0 10px;">📝 Summary</h3>
        <p style="margin: 0; line-height: 1.6;">${review.summary || 'No summary available'}</p>
      </div>

      ${review.positives && review.positives.length > 0 ? `
        <div style="background: #f0fdf4; padding: 20px; border-radius: 12px; margin-bottom: 20px; border-left: 4px solid #22c55e;">
          <h3 style="color: #22c55e; margin: 0 0 10px;">✅ Positives</h3>
          <ul style="margin: 0; padding-left: 20px;">
            ${review.positives.map(p => `<li style="margin-bottom: 8px;">${p}</li>`).join('')}
          </ul>
        </div>
      ` : ''}

      ${review.bugs && review.bugs.length > 0 ? `
        <div style="background: #fef2f2; padding: 20px; border-radius: 12px; margin-bottom: 20px; border-left: 4px solid #ef4444;">
          <h3 style="color: #ef4444; margin: 0 0 15px;">🐛 Bugs Found (${review.bugs.length})</h3>
          ${review.bugs.map(bug => `
            <div style="background: white; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
              <div style="display: flex; gap: 10px; margin-bottom: 8px;">
                <span style="background: ${bug.severity === 'critical' ? '#dc2626' : bug.severity === 'high' ? '#f97316' : bug.severity === 'medium' ? '#eab308' : '#22c55e'}; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; text-transform: uppercase;">${bug.severity}</span>
                ${bug.line && bug.line !== 'N/A' ? `<span style="color: #666; font-size: 12px;">Line ${bug.line}</span>` : ''}
              </div>
              <p style="margin: 0 0 8px; font-weight: 500;">${bug.description}</p>
              ${bug.fix ? `<p style="margin: 0; color: #22c55e; font-size: 14px;"><strong>Fix:</strong> ${bug.fix}</p>` : ''}
            </div>
          `).join('')}
        </div>
      ` : ''}

      ${review.security && review.security.length > 0 ? `
        <div style="background: #fefce8; padding: 20px; border-radius: 12px; margin-bottom: 20px; border-left: 4px solid #eab308;">
          <h3 style="color: #ca8a04; margin: 0 0 15px;">🔒 Security Issues (${review.security.length})</h3>
          ${review.security.map(sec => `
            <div style="background: white; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
              <p style="margin: 0 0 5px; font-weight: 500;">${sec.vulnerability}</p>
              <p style="margin: 0; color: #666; font-size: 14px;">${sec.description}</p>
            </div>
          `).join('')}
        </div>
      ` : ''}

      ${review.optimizations && review.optimizations.length > 0 ? `
        <div style="background: #eff6ff; padding: 20px; border-radius: 12px; margin-bottom: 20px; border-left: 4px solid #3b82f6;">
          <h3 style="color: #3b82f6; margin: 0 0 15px;">⚡ Optimizations (${review.optimizations.length})</h3>
          ${review.optimizations.map(opt => `
            <div style="background: white; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
              <span style="background: #dbeafe; color: #1d4ed8; padding: 2px 8px; border-radius: 4px; font-size: 12px;">${opt.type}</span>
              <p style="margin: 10px 0 5px; font-weight: 500;">${opt.description}</p>
              ${opt.suggestion ? `<p style="margin: 0; color: #666; font-size: 14px;">${opt.suggestion}</p>` : ''}
            </div>
          `).join('')}
        </div>
      ` : ''}

      <div style="background: #1e1e1e; padding: 20px; border-radius: 12px; margin-bottom: 20px;">
        <h3 style="color: #fff; margin: 0 0 15px;">📄 Original Code (${language})</h3>
        <pre style="margin: 0; color: #d4d4d4; font-family: 'Consolas', monospace; font-size: 12px; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word;">${code.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
      </div>

      ${review.improvedCode ? `
        <div style="background: #1e1e1e; padding: 20px; border-radius: 12px;">
          <h3 style="color: #22c55e; margin: 0 0 15px;">✨ Improved Code</h3>
          <pre style="margin: 0; color: #d4d4d4; font-family: 'Consolas', monospace; font-size: 12px; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word;">${review.improvedCode.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
        </div>
      ` : ''}

      <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
        <p style="color: #999; font-size: 12px;">
          Generated by CodeReview AI • Powered by Gemini AI
        </p>
      </div>
    </div>
  `;

  const opt = {
    margin: 10,
    filename: `code-review-${Date.now()}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(content).save();
};
